import { AbilityCategory, ItemCategory } from './enums';
import { ItemT } from './types';

export const items: Array<ItemT> = [
    {
        name: "Basic Magazine",
        cost: 500,
        category: ItemCategory.Weapon,
        tier: 1,
        attributes: ["+24% Ammo", "+15% Weapon Damage"],
        isComponentOf: "Titanic Magazine",
    },
    {
        name: "Close Quarters",
        cost: 500,
        category: ItemCategory.Weapon,
        tier: 1,
        attributes: ["+85 Bullet Shield Health"],
        abilities: [{
            description: "Deal additional Weapon Damage when in close range to your target.",
            attributes: ["+25% Weapon Damage", "15m Close Range"],
            category: AbilityCategory.Passive,
        }],
        isComponentOf: "Point Blank",
    },
    {
        name: "Headshot Booster",
        cost: 500,
        category: ItemCategory.Weapon,
        tier: 1,
        attributes: ["+5% Fire Rate", "+40 Bonus Health"],
        abilities: [{
            description: "Deal bonus Weapon Damage with headshots.",
            cooldown: 7,
            attributes: ["+45 Head Shot Bonus Damage"],
            category: AbilityCategory.Passive,
        }],    
    },
    {
        name: "Hollow Point Ward",
        cost: 500,
        category: ItemCategory.Weapon,
        tier: 1,
        attributes: ["+80 Spirit Shield Health", "+4 Spirit Power"],
        abilities: [{
            description: "When you are above 60% health, deal additional Weapon Damage.",
            attributes: ["+20% Weapon Damage"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Monster Rounds",
        cost: 500,
        category: ItemCategory.Weapon,
        tier: 1,
        attributes: ["+35% Weapon Damage vs. NPCs", "+65 Bonus Health", "+1 Health Regen"]
    },
    {
        name: "Rapid Rounds",
        cost: 500,
        category: ItemCategory.Weapon,
        tier: 1,
        attributes: ["+12% Fire Rate", "+1m/s Sprint Speed", "-50 Max Health"]

    },
    {
        name: "Restorative Rounds",
        cost: 500,
        category: ItemCategory.Weapon,
        tier: 1,
        attributes: ["+7% Bullet Resist", "+6% Weapon Damage"],
        abilities: [{
            description: "Your next bullet will heal you based on what target you hit.",
            cooldown: 6,
            attributes: ["30 Healing From Heroes", "10 Healing From NPCs"],
            category: AbilityCategory.Passive,
        }],
        },
    {
        name: "Active Reload",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        attributes: ["+10% Weapon Damage", "-20% Reload Time"],
        abilities: [{
            description: "While reloading, pressing [Reload] during the highlighted portion will instantly finish your reload and grant you Fire Rate and Bullet Lifesteal.",
            cooldown: 17,
            attributes: ["+24% Fire Rate", "+40% Bullet Lifesteal", "8s Duration"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Berserker",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        attributes:["+4 Ammo","+8% Bullet Resist"],
        abilities: [{
            description: "Your Weapon Damage increases as you take sustained damage.",
            attributes: ["+5% Weapon Damage per Stack", "110 Damage taken to Stack | 10 Max Stacks | 10s Duration"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Kinetic Dash",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        attributes:["+100 Bonus Health","+1 Health Regen"],
        abilities: [{
            description: "Your next Dash-Jump does not cost an extra stamina and you gain Fire Rate and bonus Ammo until your next reload. Lasts up to 8s.",
            attributes: ["+30% Fire Rate", "+5 Temporary Ammo", "8s Duration"],
            cooldown: 10,
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Long Range",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        attributes:["+20% Ammo"],
        abilities: [{
            description: "Deal additional Weapon Damage when beyond a minimum distance from your target.",
            attributes: ["+40% Weapon Damage", "18m Min. Distance"],
            category: AbilityCategory.Passive,
        }],
        isComponentOf: "Sharpshooter",
    },
    {
        name: "Melee Charge",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        attributes:["+15% Weapon Damage","+100 Bonus Health"],
        abilities: [{
            description: "Increases your Heavy Melee charge distance. When you perform a Heavy Melee attack against an enemy, your weapon reloads instantly.",
            attributes: [],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Mystic Shot",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        attributes:["+12% Weapon Damage","+4 Spirit Power"],
        abilities: [{
            description: "Your next bullet deals bonus Spirit Damage.",
            cooldown: 5,
            attributes: ["+65 Spirit Damage"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Slowing Bullets",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        attributes:["+16% Weapon Damage"],
        abilities: [{
            description: "Your bullets apply Movement Slow.",
            attributes: ["+25% Movement Slow", "1.3s Slow Duration"],
            category: AbilityCategory.Passive,
        }],
        isComponentOf: "Silencer",
    },
    {
        name: "Soul Shredder Bullets",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        abilities: [{
            description: "Your bullets apply a debuff that amplifies your Spirit Damage against the target and grants you Spirit Lifesteal against them.",
            attributes: ["10% Spirit Amp", "+20% Spirit Lifesteal", "5s Debuff Duration"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Swift Striker",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        attributes:["+22% Fire Rate", "-5% Bullet Resist"],
    },
    {
        name: "Fleetfoot",
        cost: 1250,
        category: ItemCategory.Weapon,
        tier: 2,
        attributes:["+75 Bonus Health", "+25% Slide Distance"],
        abilities: [{
            description: "Removes the Movement Speed penalty while shooting.",
            category: AbilityCategory.Passive,
        },
        {
            description: "Gain bonus Movement Speed and Ammo.",
            cooldown: 22,
            attributes: ["+4m/s Movement Speed", "+30% Temporary Ammo", "4s Duration"],
            category: AbilityCategory.Active,    
        }],
    },
    {
        name: "Burst Fire",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+12% Fire Rate", "+50% Slide Distance"],
        abilities: [{
            description: "Briefly gain Fire Rate and Move Speed when one of your bullets hits an enemy hero.",
            cooldown: 8,
            attributes: ["+30% Fire Rate", "+2 m/s Move Speed", "3s Duration"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Escalating Resilience",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+14% Fire Rate", "+14% Weapon Damage"],
        abilities: [{
            description: "Grants Bullet Resist when your bullets hit an enemy hero. Each shot can only grant one stack.",
            attributes: ["+30% Max Bullet Resist", "2% Bullet Resist per Stack | 20s Stack Duration"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Hunter's Aura",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+150 Bonus Health"],
        abilities: [{
            description: "Reduces nearby enemies' Bullet Resist and Fire Rate, If there is only one enemy hero nearby, this effect is tripled.",
            attributes: ["-10% Bullet Resist", "10% Fire Rate Slow", "15m Radius"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Intensifying Magazine",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+25% Ammo, +20% Weapon Damage"],
        abilities: [{
            description: "Increases Weapon Damage as you continuously fire your weapon.",
            attributes: ["+75% Max Weapon Damage", "3.5s Time for Max Damage"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Point Blank",
        cost: 3500,
        components: ["Close Quarters"],
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+300 Bullet Shield Health", "+1 Stamina"],
        abilities: [{
            description: "When in close range to your target, gain Weapon Damage and your bullets apply a Movement Slow.",
            attributes: ["+45% Weapon Damage", "25% Movement Slow", "2s Slow Duration | 15m Close Range"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Pristine Emblem",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+25% Weapon Damage", "+12 Spirit Power", "+12% Spirit Resist"],
        abilities: [{
            description: "Your attacks have additional Weapon Damage against enemies above 50% health.",
            attributes: ["+25% Weapon Damage"],
            category: AbilityCategory.Passive,
        }],
        isNew: true,
    },
    {
        name: "Sharpshooter",
        cost: 4250,
        components: ["Long Range"],
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+20% Ammo", "+15% Weapon Fall-off Range", "+35% Weapon Zoom"],
        abilities: [{
            description: "Deal additional Weapon Damage when beyond a minimum distance from your target.",
            attributes: ["+60% Weapon Damage", "18m Min. Distance"],
            category: AbilityCategory.Passive,
        },
        {
            description: "Deal bonus Weapon Damage with headshots.",
                attributes: ["+100 Headshot Bonus Damage", "3s Cooldown"],
                category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Tesla Bullets",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+14% Fire Rate"],
        abilities: [{
            description: "Your bullets have a chance to shock your target. The shock will jump to a nearby enemy.",
            attributes: ["30 Shock Damage", "60 Damage on Jump | 25% Proc Change | 8m Jump Radius | 2 Max Jumps"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Titanic Magazine",
        cost: 3500,
        components: ["Basic Magazine"],
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+100% Ammo", "+16% Weapon Damage", "+8% Bullet Resist"],
    },
    {
        name: "Toxic Bullets",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        abilities: [{
            description: "Your bullets build up a Bleed on enemies, causing them to lose a percentage of their current health over time. Also applies Healing Reduction on the bleeding target.",
            attributes: ["6%/sec Bleed Damage", "-55% Healing Reduction", "3s Duration | 0.8% Buildup Per Shot"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Alchemical Fire",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+175 Bullet Shield Health", "+14% Weapon Damage", "+7 Spirit Power"],
        abilities: [{
            description: "Throw a flask that explodes on contact, creating an area that does increasing Spirit Damage per second and causes enemies to receive additional Weapon Damage from your team. Deals 40% less DPS vs non-heroes.",
            cooldown: 28,
            attributes: ["45 DPS", "+50% Weapon Damage", "95 Max DPS | 10m Radius | 5s Duration"],
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Heroic Aura",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+18% Bullet Lifesteal", "+150 Bonus Health", "+1 m/s Move Speed"],
        abilities: [{
            description: "Provide Fire Rate to nearby player minions.",
            attributes: ["+40% Minions Fire Rate", "20m Radius"],
            category: AbilityCategory.Passive,
        },
        {
            description: "Provides bonus Movement Speed and Fire Rate to you and nearby allies.",
            cooldown: 30,
            attributes: ["+3m/s Movement Speed", "+25% Fire Rate", "30m Active Radius | 5s Duration"],
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Warp Stone",
        cost: 3000,
        category: ItemCategory.Weapon,
        tier: 3,
        attributes:["+20% Weapon Damage", "+2m/s Sprint Speed"],
        abilities: [{
            description: "Teleport straight ahead, gaining Bullet Resist.",
            cooldown: 15,
            attributes: ["13m Teleport Range", "+60% Bullet Resist", "5s Buff Duration"],
            category: AbilityCategory.Active,
        },]
    },
    {
        name: "Crippling Headshot",
        cost: 6300,
        category: ItemCategory.Weapon,
        tier: 4,
        attributes:["+20% Weapon Damage", "+10% Bullet Lifesteal", "+10% Spirit Lifesteal"],
        abilities: [{
            description: "Headshots reduce target's Bullet and Spirit Resist.",
            attributes: ["24% Bullet Resist Reduction", "24% Spirit Resist Reduction", "5s Debuff Duration"],
            category: AbilityCategory.Passive,
        },]
    },
    {
        name: "Frenzy",
        cost: 6300,
        category: ItemCategory.Weapon,
        tier: 4,
        attributes:["+9 Ammo", "+30% Weapon Damage", "+200 Bonus Health"],
        abilities: [{
            description: "While you are below 40% health, you gain stat bonuses.",
            attributes: ["4 m/s Movement Speed", "40% Fire Rate", "45% Spirit Resist"],
            category: AbilityCategory.Passive,
        },]
    },
    {
        name: "Glass Cannon",
        cost: 6300,
        category: ItemCategory.Weapon,
        tier: 4,
        attributes:["+75% Weapon Damage", "+10% Fire Rate", "-15% Max Health"],
        abilities: [{
            description: "Each hero kill grants permanent +2 ammo (up to max of +14).",
            attributes: ["+2 Bonus Ammo Per Kill"],
            category: AbilityCategory.Passive,
        },]
    },
    {
        name: "Lucky Shot",
        cost: 6300,
        category: ItemCategory.Weapon,
        tier: 4,
        attributes:["+30% Ammo"],
        abilities: [{
            description: "Your bullets have a chance to be empowered causing them to deal bonus damage and Slow on hit.",
            attributes: ["80% Bonus Damage", "30% Movement Slow", "30% Proc Chance | 1.5s Slow Duration"],
            category: AbilityCategory.Passive,
        },]
    },
    {
        name: "Ricochet",
        cost: 6300,
        category: ItemCategory.Weapon,
        tier: 4,
        attributes:["+35% Ammo", "+125 Bonus Health", "+8% Fire Rate"],
        abilities: [{
            description: "Your bullets will ricochet on enemies near your target, applying any bullet procs and dealing a percentage of the original damage.",
            attributes: ["50% Ricochet Damage", "2 Ricochet Targets | 14m Ricochet Range"],
            category: AbilityCategory.Passive,
        },]
    },
    {
        name: "Siphon Bullets",
        cost: 6300,
        category: ItemCategory.Weapon,
        tier: 4,
        attributes:["+40% Weapon Damage"],
        abilities: [{
            description: "Your bullets temporarily steal Max HP from enemies. Enemies regain their stolen health when the debuff expires.",
            attributes: ["45 Max HP Steal Per Bullet", "20s Steal Duration | 0.8s Max Frequency"],
            category: AbilityCategory.Passive,
        },]
    },
    {
        name: "Spiritual Overflow",
        cost: 6300,
        category: ItemCategory.Weapon,
        tier: 4,
        attributes:["+20% Fire Rate", "+15% Cooldown Reduction", "+10% Spirit Lifesteal"],
        abilities: [{
            description: "Gain bonus Spirit Power by charging up with your bullets on enemy heroes.",
            attributes: ["+45 Spirit Power", "0.8% Buildup Per Shot | 18s Duration"],
            category: AbilityCategory.Passive,
        },]
    },
    {
        name: "Silencer",
        cost: 7550,
        components: ["Slowing Bullets"],
        category: ItemCategory.Weapon,
        tier: 4,
        attributes:["+25% Bullet Slow Proc", "15% Weapon Damage"],
        abilities: [{
            description: "For the next 6s, all your bullets immediately apply Silence. Silence prevents targets from using abilities",
            cooldown:34,
            attributes: ["Silenced", "2s Debuff Duration"],
            category: AbilityCategory.Active,
        },]
    },
    {
        name: "Vampiric Burst",
        cost: 6300,
        category: ItemCategory.Weapon,
        tier: 4,
        attributes:["+2 m/s Move Speed", "+25% Weapon Damage", "+150 Bonus Health"],
        abilities: [{
            description: "Grants Lifesteal, Fire Rate, and Ammo. This added Ammo is not limited by your max magazine size.",
            cooldown: 35,
            attributes: ["100% Bullet Lifesteal", "40% Fire Rate", "+50% Ammo | 4.5s Duration"],
            category: AbilityCategory.Active,
        },]
    },
    {
        name: "Enduring Spirit",
        cost: 500,
        category: ItemCategory.Vitality,
        tier: 1,
        attributes: ["+75 Bonus Health", "+8% Spirit Lifesteal", "+4 Spirit Power"],
    },
    {
        name: "Extra Health",
        cost: 500,
        category: ItemCategory.Vitality,
        tier: 1,
        attributes: ["+160 Bonus Health", "+5% Weapon Damage"],
    },
    {
        name: "Extra Regen",
        cost: 500,
        category: ItemCategory.Vitality,
        tier: 1,
        attributes: ["+2.7 Health Regen", "+8% Ammo", "+25 Bonus Health"]
    },
    {
        name: "Extra Stamina",
        cost: 500,
        category: ItemCategory.Vitality,
        tier: 1,
        attributes: ["+1 Stamina", "+10% Stamina Recovery", "+7% Fire Rate"],
        isComponentOf: "Superior Stamina",
    },
    {
        name: "Melee Lifesteal",
        cost: 500,
        category: ItemCategory.Vitality,
        tier: 1,
        attributes: ["+15% Melee Damage", "+70 Bonus Health"],
        abilities: [{
            description: "Your Melee attacks heal you for 20% of the Melee Damage dealt plus 90. This heal is 25% effective vs non-heroes.",
            cooldown: 7,
            category: AbilityCategory.Passive,
        }],
        isComponentOf: "Lifestrike"
    },
    {
        name: "Sprint Boots",
        cost: 500,
        category: ItemCategory.Vitality,
        tier: 1,
        attributes: ["+2m/s Sprint Speed", "+1 Health Regen", "+4% Weapon Damage"],
        isComponentOf: "Enduring Speed"
    },
    {
        name: "Healing Rite",
        cost: 500,
        category: ItemCategory.Vitality,
        tier: 1,
        attributes: ["+45 Bonus Health"],
        abilities: [{
            description: "Grant Regen and Sprint Speed to the target. Gets dispelled if you take damage from enemy players or objectives. Can be self-cast.",
            category: AbilityCategory.Active,
            cooldown: 75,
            attributes: ["370 Total HP Regen", "+2m/s Sprint Speed", "17s Regen Duration | 20m Cast Range"],
        }],
        isComponentOf: "Rescue Beam"
    },
    {
        name: "Bullet Armor",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+20% Bullet Resist", "+6% Weapon Damage"],
        isComponentOf: "Improved Bullet Armor"
    },
    {
        name: "Bullet Lifesteal",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+25% Bullet Lifesteal", "+75 Bonus Health"]
    },
    {
        name: "Combat Barrier",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+300 Bullet Shield Health"],
        abilities: [{
            description: "While you have a Bullet Shield, gain Weapon Damage.",
            attributes: ["+24% Weapon Damage While Shielded"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Debuff Reducer",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+75 Bonus Health", "+6% Weapon Damage"],
        abilities: [{
            description: "Reduces the duration of all negative effects applied to you.",
            attributes: ["30% Debuff Duration"],
            category: AbilityCategory.Passive,
        }],
        isComponentOf: "Debuff Remover"
    },
    {
        name: "Enchanter's Barrier",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+300 Spirit Shield Health"],
        abilities: [{
            description: "While you have a Spirit Shield, gain bonus Spirit Power.",
            attributes: ["+17 Spirit Power While Shielded"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Enduring Speed",
        cost: 1750,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+1.4/s Move Speed","+2m/s Sprint Speed", "+75 Bonus Health", "+1.5 Health Regen"],
        abilities: [{
            description: "Reduces the effect of enemy Movement Slow.",
            attributes: ["+40% Movement Slow Resist"],
            category: AbilityCategory.Passive,
        }],
        components: ["Sprint Boots"]
    },
    {
        name: "Healbane",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+75 Bonus Health"],
        abilities: [{
            description: "Your Spirit Damage applies Healing Reduction. If an enemy hero dies under this effect, you receive a large heal.",
            attributes: ["-40% Healing Reduction","350 Heal On Hero Kill","6s Duration"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Healing Booster",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+7% Spirit Resist", "+7% Bullet Resist", "+2 Health Regen"],
        abilities: [{
            description: "Increases the effectiveness of your Healing by 25%.",
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Reactive Barrier",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+15% Ammo", "+75 Bonus Health", "+2 Health Regen"],
        abilities: [{
            description: "Automatically deploy temporary Bullet and Spirit Shields when you are movement locked, Stunned, Chained, Immobilized, or Slept.",
            attributes: ["400 Bullet Shield Health", "200 Spirit Shield Health" ,"13s Duration"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Spirit Armor",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+20% Spirit Resist", "+5 Spirit Power"],
        isComponentOf: "Improved Spirit Armor"
    },
    {
        name: "Spirit Lifesteal",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+23% Spirit Lifesteal", "+75 Bonus Health"]
    },
    {
        name: "Divine Barrier",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+7% Bullet Resist", "+1.5 Health Regen"],
        abilities: [{
            description: "Provide the target with Bullet Shield, Spirit Shield, and Movement Speed. Can be self-cast.",
            attributes: ["300 Bullet Shield", "300 Spirit Shield", "+2m/s Movement Speed", "4s Duration | 35m Cast Range"],
            cooldown: 30,
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Health Nova",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+10% Weapon Damage", "+75 Bonus Health"],
        abilities: [{
            description: "Heal yourself and nearby allies. Heals an additional 20% per ally.",
            cooldown: 60,
            attributes: ["260 Total HP Regen", "2s Regen Duration | 18m Radius"],
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Restorative Locket",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+10% Spirit Resist", "+5 Spirit Power"],
        abilities: [{
            description: "When an enemy uses an ability within 50m range from you, store one Restoration Stack.",
            category: AbilityCategory.Passive,
        }, 
        {
            description: "Consume all stacks to heal target ally. If used at max stacks, it fully replenishes the target's stamina. Can be self-cast.",
            cooldown: 24,
            attributes: ["30 Heal Per Stack", "20 Max Stacks"],
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Return Fire",
        cost: 1250,
        category: ItemCategory.Vitality,
        tier: 2,
        attributes: ["+125 Bonus Health", "+7 Spirit Power", "+7% Fire Rate"],
        abilities: [{
            description: "Automatically fire a bullet towards any attacker who damages you with their abilities or weapon",
            cooldown: 24,
            attributes: ["80% Bullet Damage Returned", "30% Spirit Damage Returned", "7s Duration"],
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Fortitude",
        cost: 3000,
        category: ItemCategory.Vitality,
        tier: 3,
        attributes: ["+275 Bonus Health"],
        abilities: [{
            description: "After not taking damage for 13s, gain 4% Max Health Regen.",
            category: AbilityCategory.Passive,
        },
        {
            description: "When you are above 75% health, you have bonus Weapon Damage and Movement Speed.",
            attributes: ["+25% Weapon Damage", "+2m/s Movement Speed"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Improved Bullet Armor",
        cost: 4250,
        category: ItemCategory.Vitality,
        tier: 3,
        attributes: ["+45% Bullet Resist", "+10% Weapon Damage"],
        components: ["Bullet Armor"]
    },
    {
        name: "Improved Spirit Armor",
        cost: 4250,
        category: ItemCategory.Vitality,
        tier: 3,
        attributes: ["+45% Spirit Resist", "+8 Spirit Power"],
        components: ["Spirit Armor"]
    },
    {
        name: "Lifestrike",
        cost: 3500,
        category: ItemCategory.Vitality,
        tier: 3,
        components: ["Melee Lifesteal"],
        attributes: ["+40% Melee Damage", "+125 Bonus Health", "8% Bullet Resist"],
        abilities: [{
            description: "Your Melee Attacks applies Movement Slow and heals you for 45% of the Melee Damage dealt plus 110. This heal is 25% vs non-heroes.",
            cooldown: 5,
            attributes: ["60% Movement Slow", "2.5s Slow Duration"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Superior Stamina",
        cost: 3500,
        category: ItemCategory.Vitality,
        tier: 3,
        components: ["Extra Stamina"],
        attributes: ["+3 Stamina", "+20% Stamina Recovery", "+50% Air Jump/Dash Distance","+10% Fire Rate", "+8 Spirit Power"],
        abilities: [{
            description: "Increases the number of Air Dashes and Air Jumps that can be performed before landing from 1 to 2.",
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Veil Walker",
        cost: 3000,
        category: ItemCategory.Vitality,
        tier: 3,
        attributes: ["+200 Bullet Shield Health", "+200 Spirit Shield Health", "+12% Ammo", "10% Weapon Damage"],
        abilities: [{
            description: "Walking through a cosmic veil grants you Stealth, increased Movement Speed, restores all Bullet and Spirit Shields, and grants bonus Fire Rate for your next magazine.",
            cooldown: 18,
            attributes: ["Invisible", "3m/s Invis Move Speed", "+30% Fire Rate", "5s Invisibility Duration"],
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Debuff Remover",
        cost: 4250,
        category: ItemCategory.Vitality,
        tier: 3,
        components: ["Debuff Reducer"],
        attributes: ["+125 Bonus Health", "+20% Weapon Damage"],
        abilities: [{
            description: "Reduces the duration of all negative effects applied to you.",
            attributes: ["40% Debuff Resist"],
            category: AbilityCategory.Passive,
        },
        {
            description: "Purge all negative effects currently applied to you. If any effects were removed, gain a movement speed bonus. Cannot be used while Stunned or Slept.",
            attributes: ["+3m/s Movement Speed", "3s Duration"],
            cooldown: 45,
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Majestic Leap",
        cost: 3000,
        category: ItemCategory.Vitality,
        tier: 3,
        attributes: ["+8 Spirit Power", "+100 Bonus Health"],
        abilities: [{
            description: "Launch yourself high into the air. While in the air, you can use the active again to drop down faster. Cannot be used for 5s if attacked by enemy Hero.",
            cooldown: 26,
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Metal Skin",
        cost: 3000,
        category: ItemCategory.Vitality,
        tier: 3,
        attributes: ["+125 Bonus Health", "+8 Spirit Power", "+8% Fire Rate"],
        abilities: [{
            description: "Become immune to bullets and melee attacks.",
            attributes: ["3.5s Duration"],
            cooldown: 30,
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Rescue Beam",
        cost: 3500,
        category: ItemCategory.Vitality,
        tier: 3,
        components: ["Healing Rite"],
        attributes: ["+125 Bonus Health", "+2m/s Sprint Speed", "+9 Spirit Power"],
        abilities: [{
            description: "Heals a target allied hero and yourself for a percentage of Max Health. Once while healing, you can Pull the target towards your. Can be self-cast.",
            cooldown: 30,
            attributes: ["30% Heal Amount", "3s Channel Duration | 45m Cast Range"],
            category: AbilityCategory.Active,
        }],
    },
    {
        name: "Inhibitor",
        cost: 6300,
        category: ItemCategory.Vitality,
        tier: 4,
        attributes: ["+20% Weapon Damage", "+175 Bonus Health"],
        abilities: [{
            description: "Your bullets apply Movement Slow and reduce the target's outgoing damage on hit.",
            attributes: ["25% Movement Slow", "-35% Damage Penalty", "2.5s Debuff Duration"],
            category: AbilityCategory.Passive,
        }],
    },
    {
        name: "Leech",
        cost: 6300,
        category: ItemCategory.Vitality,
        tier: 4,
    },
    {
        name: "Soul Rebirth",
        cost: 6300,
        category: ItemCategory.Vitality,
        tier: 4,
    },
    {
        name: "Colossus",
        cost: 6300,
        category: ItemCategory.Vitality,
        tier: 4,
    },
    {
        name: "Phantom Strike",
        cost: 6300,
        category: ItemCategory.Vitality,
        tier: 4,
    },
    {
        name: "Shadow Weave",
        cost: 6300,
        category: ItemCategory.Vitality,
        tier: 4,
    },
    {
        name: "Unstoppable",
        cost: 6300,
        category: ItemCategory.Vitality,
        tier: 4,
    },
    {
        name: "Ammo Scavenger",
        cost: 500,
        category: ItemCategory.Spirit,
        tier: 1,
    },
    {
        name: "Extra Charge",
        cost: 500,
        category: ItemCategory.Spirit,
        tier: 1,
    },
    {
        name: "Extra Spirit",
        cost: 500,
        category: ItemCategory.Spirit,
        tier: 1,
    },
    {
        name: "Mystic Burst",
        cost: 500,
        category: ItemCategory.Spirit,
        tier: 1,
    },
    {
        name: "Mystic Reach",
        cost: 500,
        category: ItemCategory.Spirit,
        tier: 1,
    },
    {
        name: "Spirit Strike",
        cost: 500,
        category: ItemCategory.Spirit,
        tier: 1,
    },
    {
        name: "Infuser",
        cost: 500,
        category: ItemCategory.Spirit,
        tier: 1,
    },
    {
        name: "Bullet Resist Shredder",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Duration Extender",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Improved Cooldown",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Mystic Vulnerability",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Quicksilver Reload",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Suppressor",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Cold Front",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Decay",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Slowing Hex",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Withering Whip",
        cost: 1250,
        category: ItemCategory.Spirit,
        tier: 2,
    },
    {
        name: "Improved Burst",
        cost: 3500,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Improved Reach",
        cost: 3500,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Improved Spirit",
        cost: 3500,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Mystic Slow",
        cost: 4250,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Rapid Recharge",
        cost: 3500,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Superior Cooldown",
        cost: 4250,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Superior Duration",
        cost: 4250,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Surge of Power",
        cost: 3000,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Torment Pulse",
        cost: 3000,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Ethereal Shift",
        cost: 3000,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Knockdown",
        cost: 3000,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Silence Glyph",
        cost: 3000,
        category: ItemCategory.Spirit,
        tier: 3,
    },
    {
        name: "Boundless Spirit",
        cost: 9800,
        category: ItemCategory.Spirit,
        tier: 4,
    },
    {
        name: "Diviner's Kevlar",
        cost: 6300,
        category: ItemCategory.Spirit,
        tier: 4,
    },
    {
        name: "Escalating Exposure",
        cost: 7550,
        category: ItemCategory.Spirit,
        tier: 4,
    },
    {
        name: "Mystic Reverb",
        cost: 6300,
        category: ItemCategory.Spirit,
        tier: 4,
    },
    {
        name: "Curse",
        cost: 6300,
        category: ItemCategory.Spirit,
        tier: 4,
    },
    {
        name: "Echo Shard",
        cost: 6300,
        category: ItemCategory.Spirit,
        tier: 4,
    },
    {
        name: "Refresher",
        cost: 6300,
        category: ItemCategory.Spirit,
        tier: 4,
    },
];